# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        clean: false 
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - name: Write .env file from secrets
      run: |
        cat <<EOF > server/.env
        PORT=${{ secrets.PORT }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_KEY=${{ secrets.JWT_KEY }}
        MONGODB_URI=${{ secrets.MONGODB_URI }}
        AWS_REGION=${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
        RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}
        RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}
        RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
        RAZORPAY_WEBHOOK_URL=${{ secrets.RAZORPAY_WEBHOOK_URL }}
        BUCKET_NAME=${{ secrets.BUCKET_NAME }}
        EOF
    # - name: Install dependencies
    #   run: npm ci
    #   working-directory: server  # 👈 run inside server/
    - name: Restart PM2 process
      run: pm2 restart peekbi
      working-directory: server
